In [3]:
import pandas as pd
df = pd.read_csv(r'C:\Users\vrish\OneDrive\Desktop\LbCDA\data.csv')

In [39]:
import numpy as np
df.replace(-1, np.nan, inplace=True)

In [41]:

df["Location_Missing"] = (
    df["Latitude"].isnull() |
    df["Longitude"].isnull()
).astype(int)

df["Latitude"] = df["Latitude"].fillna(-999)

df["Longitude"] = df["Longitude"].fillna(-999)

In [16]:
df["Location_Missing"] = 0

df.loc[df["State Name"] == "Unknown", "Location_Missing"] = 1

In [13]:
print(df.columns)

Index(['Operator', 'Rating', 'Call Drop Category', 'Latitude', 'Longitude',
       'In Out Travelling_Indoor', 'In Out Travelling_Outdoor',
       'In Out Travelling_Travelling', 'Network Type_2G', 'Network Type_3G',
       'Network Type_4G', 'Network Type_Unknown', 'State_Andhra Pradesh',
       'State_Assam', 'State_Bihar', 'State_California', 'State_Chandigarh',
       'State_Chhattisgarh', 'State_Goa', 'State_Gujarat', 'State_Haryana',
       'State_Himachal Pradesh', 'State_Jharkhand', 'State_Karnataka',
       'State_Kashmir', 'State_Kerala', 'State_Madhya Pradesh',
       'State_Maharashtra', 'State_Manipur', 'State_Meghalaya',
       'State_Mid Western', 'State_NCT', 'State_Nagaland', 'State_Odisha',
       'State_Pondicherry', 'State_Punjab', 'State_Rajasthan', 'State_Sikkim',
       'State_Tamil Nadu', 'State_Telangana', 'State_Tripura',
       'State_Uttar Pradesh', 'State_Uttarakhand', 'State_West Bengal'],
      dtype='object')

In [16]:
df=pd.get_dummies(df,
    columns=['Operator'],dtype=int)

In [12]:
operator_cols = [
    "Operator_Airtel",
    "Operator_BSNL",
    "Operator_Idea",
    "Operator_MTNL",
    "Operator_Other",
    "Operator_RJio",
    "Operator_Telenor",
    "Operator_Vodafone"
]

df[operator_cols] = df[operator_cols].astype(int)

KeyError: "None of [Index(['Operator_Airtel', 'Operator_BSNL', 'Operator_Idea', 'Operator_MTNL',\n       'Operator_Other', 'Operator_RJio', 'Operator_Telenor',\n       'Operator_Vodafone'],\n      dtype='object')] are in the [columns]"

In [9]:
df = pd.get_dummies(df, columns=["State Name"], prefix="State")

In [21]:
state_cols = [
    "State_Punjab",
    "State_Rajasthan",
    "State_Sikkim",
    "State_Tamil Nadu",
    "State_Telangana",
    "State_Tripura",
    "State_Uttar Pradesh",
    "State_Uttarakhand",
    "State_West Bengal",
    #"State_Unknown"
]

df[state_cols] = df[state_cols].astype(int)

In [6]:
df = pd.get_dummies(
    df,
    columns=[
        "In Out Travelling",
        "Network Type",
    ],
    dtype=int
)

In [23]:
df.head(200)

,Rating,Call Drop Category,Latitude,Longitude,In Out Travelling_Indoor,In Out Travelling_Outdoor,In Out Travelling_Travelling,Network Type_2G,Network Type_3G,Network Type_4G,...,State_Uttarakhand,State_West Bengal,Operator_Airtel,Operator_BSNL,Operator_Idea,Operator_MTNL,Operator_Other,Operator_RJio,Operator_Telenor,Operator_Vodafone
0,2,Poor Voice Quality,26.483777,80.319767,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,5,Satisfactory,21.258587,81.567728,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,2,Poor Voice Quality,-1.000000,-1.000000,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,5,Satisfactory,-1.000000,-1.000000,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,4,Satisfactory,20.278975,85.836103,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,Poor Voice Quality,12.892068,77.607249,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
196,4,Satisfactory,-1.000000,-1.000000,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
197,3,Poor Voice Quality,22.574076,88.420788,0,0,1,0,0,1,...,0,1,0,0,0,0,0,0,0,1
198,2,Poor Voice Quality,26.483835,80.319869,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
199,4,Satisfactory,-1.000000,-1.000000,1,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0

In [25]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df["Call Drop Category"] = le.fit_transform(df["Call Drop Category"])

In [26]:
df.head()

,Rating,Call Drop Category,Latitude,Longitude,In Out Travelling_Indoor,In Out Travelling_Outdoor,In Out Travelling_Travelling,Network Type_2G,Network Type_3G,Network Type_4G,...,State_Uttarakhand,State_West Bengal,Operator_Airtel,Operator_BSNL,Operator_Idea,Operator_MTNL,Operator_Other,Operator_RJio,Operator_Telenor,Operator_Vodafone
0,2,1,26.483777,80.319767,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,5,2,21.258587,81.567728,0,1,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,2,1,-1.000000,-1.000000,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,5,2,-1.000000,-1.000000,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,4,2,20.278975,85.836103,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [42]:
df.to_csv(r"C:\Users\vrish\OneDrive\Desktop\LbCDA\data.csv", index=False)

In [30]:
state_cols = [
    "State_Andhra Pradesh",
    "State_Assam",
    "State_Bihar",
    "State_California",
    "State_Chandigarh",
    "State_Chhattisgarh",
    "State_Goa",
    "State_Gujarat",
    "State_Haryana",
    "State_Himachal Pradesh",
    "State_Jharkhand",
    "State_Karnataka",
    "State_Kashmir",
    "State_Kerala",
    "State_Madhya Pradesh",
    "State_Maharashtra",
    "State_Manipur",
    "State_Meghalaya",
    "State_Mid Western",
    "State_NCT",
    "State_Nagaland",
    "State_Odisha",
    "State_Pondicherry"
]

df[state_cols] = df[state_cols].astype(int)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33812 entries, 0 to 33811
Data columns (total 51 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Rating                        33812 non-null  int64
 1   Call Drop Category            33812 non-null  int64
 2   Latitude                      33812 non-null  float64
 3   Longitude                     33812 non-null  float64
 4   In Out Travelling_Indoor      33812 non-null  int64
 5   In Out Travelling_Outdoor     33812 non-null  int64
 6   In Out Travelling_Travelling  33812 non-null  int64
 7   Network Type_2G               33812 non-null  int64
 8   Network Type_3G               33812 non-null  int64
 9   Network Type_4G               33812 non-null  int64
 10  Network Type_Unknown          33812 non-null  int64
 11  State_Andhra Pradesh          33812 non-null  int64
 12  State_Assam                   33812 non-null  int64
 13  State_Bihar                   33812 non-null  int64
 14  State_California              33812 non-null  int64
 15  State_Chandigarh              33812 non-null  int64
 16  State_Chhattisgarh            33812 non-null  int64
 17  State_Goa                     33812 non-null  int64
 18  State_Gujarat                 33812 non-null  int64
 19  State_Haryana                 33812 non-null  int64
 20  State_Himachal Pradesh        33812 non-null  int64
 21  State_Jharkhand               33812 non-null  int64
 22  State_Karnataka               33812 non-null  int64
 23  State_Kashmir                 33812 non-null  int64
 24  State_Kerala                  33812 non-null  int64
 25  State_Madhya Pradesh          33812 non-null  int64
 26  State_Maharashtra             33812 non-null  int64
 27  State_Manipur                 33812 non-null  int64
 28  State_Meghalaya               33812 non-null  int64
 29  State_Mid Western             33812 non-null  int64
 30  State_NCT                     33812 non-null  int64
 31  State_Nagaland                33812 non-null  int64
 32  State_Odisha                  33812 non-null  int64
 33  State_Pondicherry             33812 non-null  int64
 34  State_Punjab                  33812 non-null  int64
 35  State_Rajasthan               33812 non-null  int64
 36  State_Sikkim                  33812 non-null  int64
 37  State_Tamil Nadu              33812 non-null  int64
 38  State_Telangana               33812 non-null  int64
 39  State_Tripura                 33812 non-null  int64
 40  State_Uttar Pradesh           33812 non-null  int64
 41  State_Uttarakhand             33812 non-null  int64
 42  State_West Bengal             33812 non-null  int64
 43  Operator_Airtel               33812 non-null  int64
 44  Operator_BSNL                 33812 non-null  int64
 45  Operator_Idea                 33812 non-null  int64
 46  Operator_MTNL                 33812 non-null  int64
 47  Operator_Other                33812 non-null  int64
 48  Operator_RJio                 33812 non-null  int64
 49  Operator_Telenor              33812 non-null  int64
 50  Operator_Vodafone             33812 non-null  int64
dtypes: float64(2), int64(49)
memory usage: 13.2 MB